# Generated by Django 6.0 on 2026-01-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("age", models.IntegerField(default=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
