# Generated by Django 6.0 on 2026-01-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_teacherprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="attendance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
