# Generated by Django 6.0 on 2026-01-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='salary',
        ),
    ]
