# Generated by Django 6.0 on 2026-01-11 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0003_studentprofile_attendance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="studentmarks",
            name="marks_obtained",
        ),
        migrations.AddField(
            model_name="studentmarks",
            name="marks",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assessmenttype",
            name="max_marks",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="semester",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="studentmarks",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_marks",
                to="accounts.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "TEACHER"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together={("teacher", "subject", "semester")},
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("present", models.BooleanField(default=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.teacherassignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "assignment", "date")},
            },
        ),
    ]
